### ISSUE TITLE
[Question] No Support for MacOS

### ISSUE THREAD

**Issue by SlootSantos** [TechQuery/Puppeteer-IE#3]
Hey guys,

Am I right assuming that this won't work on MacOS or Linux without effort to virtualize?
`wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"}`

**Comment by TechQuery** [comment]
This package controls a **real IE browser** through **COM+** (ActiveX) interface in your Windows, if you want write Cross-platform scripts with only one package, please use https://web-cell.tk/puppeteer-browser/.
